import { PrismaPg } from '@prisma/adapter-pg';

import { Prisma, PrismaClient } from './generated/prisma/client.js';

export { Prisma, PrismaClient };
export {
  AttachmentOwnerType,
  AttachmentScanStatus,
  AttachmentStatus,
  AuditActorType,
  CustomerType,
  DailyReportStatus,
  EmploymentStatus,
  EmploymentType,
  MemberStatus,
  NotificationSeverity,
  OrgStatus,
  PermissionScope,
  PlatformAuditActorType,
  PlatformRole,
  ProjectActivitySource,
  ProjectHealth,
  ProjectRole,
  ProjectStatus,
  WorkLocationType,
  TicketSource,
  TicketSeverity,
  TicketPriority,
  TicketImpact,
  TicketStatus,
  SlaState,
  TicketCommentVisibility,
  SlaEventKind,
  EscalationTrigger,
  NotificationChannel,
  NotificationDeliveryStatus,
  NotificationCategory,
  NotificationPreferenceChannel,
  JiraAuthType,
  JiraConnectionStatus,
  JiraImportState,
  JiraStatusCategory,
  JiraSyncRunType,
  JiraSyncRunStatus,
  JiraFailureClass,
  JiraWebhookDeliveryStatus,
  TicketJiraLinkType,
  TicketJiraLinkSource,
  JiraCreateRequestStatus,
  RetentionCategory,
  RetentionAction,
  GithubInstallationStatus,
  GithubAccountType,
  GithubRepositorySelection,
  GithubRepositoryStatus,
  GithubSyncState,
  GithubPullRequestState,
  GithubReviewState,
  GithubChecksState,
  GithubPrJiraLinkSource,
  GithubPrJiraLinkState,
  GithubWebhookDeliveryStatus,
  GithubSyncRunType,
  GithubSyncRunStatus,
  GithubFailureClass,
  RequestCategory,
  WorkflowVersionStatus,
  WorkflowStepKind,
  ApproverType,
  ApprovalMode,
  AttachmentRequirement,
  RequestStatus,
  RequestApprovalStatus,
  RequestEffectKind,
  RequestEffectMode,
  RequestEffectStatus,
  TenderStatus,
  TenderType,
  CommercialPriority,
  TenderBidDecision,
  BidCriterionValue,
  NoBidReason,
  TenderRequirementCategory,
  TenderRequirementStatus,
  TenderReviewGateType,
  TenderReviewMode,
  TenderReviewGateStatus,
  TenderReviewStatus,
  TenderSubmissionMethod,
  TenderSubmissionKind,
  TenderLossReason,
  TenderClarificationStatus,
  CommercialDocumentCategory,
  DocumentClassification,
  CorporateDocumentType,
  CorporateDocumentStatus,
  ContractType,
  ContractStatus,
  ContractRenewalType,
  CommercialHealth,
  ContractAmendmentType,
  ContractAmendmentStatus,
  ObligationCategory,
  ObligationCriticality,
  ObligationRecurrence,
  ObligationStatus,
  MilestoneStatus,
  GuaranteeType,
  GuaranteeStatus,
  RenewalActionType,
} from './generated/prisma/client.js';
export type {
  Attachment,
  AuditLog,
  Customer,
  DailyReport,
  Department,
  EmployeeProfile,
  JobTitle,
  MemberInvitation,
  MemberRole,
  Notification,
  Organization,
  OrganizationCounter,
  OrganizationMember,
  OutboxEvent,
  PlatformAuditLog,
  Project,
  ProjectActivity,
  ProjectLocation,
  ProjectMember,
  Role,
  RolePermission,
  Team,
  TeamMember,
  User,
  WorkLocation,
  SupportCategory,
  SupportComponent,
  BusinessCalendar,
  SlaPolicy,
  EscalationRule,
  SupportTicket,
  SupportTicketEvent,
  SupportTicketComment,
  SupportTicketWatcher,
  SlaEvent,
  NotificationDelivery,
  NotificationPreference,
  JiraConnection,
  JiraProjectMapping,
  JiraIssue,
  JiraSyncRun,
  JiraSyncFailure,
  JiraWebhookRegistration,
  JiraWebhookDelivery,
  SupportTicketJiraLink,
  JiraIssueCreateRequest,
  RetentionPolicy,
  GithubInstallation,
  GithubRepository,
  GithubRepositoryMapping,
  GithubPullRequest,
  GithubPrJiraLink,
  GithubWebhookDelivery,
  GithubSyncRun,
  GithubSyncFailure,
  SupportTicketGithubLink,
  RequestType,
  RequestTypeRole,
  WorkflowDefinition,
  WorkflowVersion,
  WorkflowStep,
  RequestInstance,
  RequestApproval,
  ApprovalDelegation,
  RequestEvent,
  RequestEffect,
  Tender,
  TenderRequirement,
  TenderReviewGate,
  TenderReview,
  Contract,
  ContractAmendment,
  ContractObligation,
  ContractObligationOccurrence,
  ContractMilestone,
  Guarantee,
  CommercialDocument,
  CorporateDocument,
  CommercialSettings,
} from './generated/prisma/client.js';

/** Creates a Prisma client over the pg driver adapter (required by Prisma 7, ADR-0006). */
export function createPrismaClient(databaseUrl: string): PrismaClient {
  return new PrismaClient({ adapter: new PrismaPg({ connectionString: databaseUrl }) });
}

export interface OperationGuard {
  /** Called before every model operation; throws to reject it. */
  readonly checkModelOperation: (model: string, operation: string, args: unknown) => void;
  /** Called instead of `$queryRawUnsafe` / `$executeRawUnsafe`; must throw. */
  readonly rejectUnsafeRaw: (operation: '$queryRawUnsafe' | '$executeRawUnsafe') => never;
}

/**
 * Applies a query-only extension that runs `guard` before every model operation, including inside
 * interactive and batch transactions. The policy lives in `@company-ops/core` (tenant guard).
 */
export function withOperationGuard(prisma: PrismaClient, name: string, guard: OperationGuard) {
  return prisma.$extends({
    name,
    query: {
      $allModels: {
        $allOperations({ model, operation, args, query }) {
          guard.checkModelOperation(model, operation, args);
          return query(args);
        },
      },
      $queryRawUnsafe() {
        return guard.rejectUnsafeRaw('$queryRawUnsafe');
      },
      $executeRawUnsafe() {
        return guard.rejectUnsafeRaw('$executeRawUnsafe');
      },
    },
  });
}

export type GuardedPrismaClient = ReturnType<typeof withOperationGuard>;
