-- Phase 10 tenders and contracts (ADR-0026): enum types first, in their own migration, so that the
-- values added to existing enums (attachment owner types, the COMMERCIAL notification category) are
-- committed before the next migration uses them.

-- CreateEnum
CREATE TYPE "TenderStatus" AS ENUM ('DRAFT', 'NEW', 'UNDER_REVIEW', 'BID_DECISION_PENDING', 'NO_BID', 'PREPARING', 'INTERNAL_REVIEW', 'READY_FOR_SUBMISSION', 'SUBMITTED', 'CLARIFICATION', 'AWARDED', 'LOST', 'CANCELLED', 'ARCHIVED');

-- CreateEnum
CREATE TYPE "TenderType" AS ENUM ('OPEN_TENDER', 'LIMITED_TENDER', 'DIRECT_INVITATION', 'RFQ', 'RFP', 'FRAMEWORK_AGREEMENT', 'OTHER');

-- CreateEnum
CREATE TYPE "CommercialPriority" AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL');

-- CreateEnum
CREATE TYPE "TenderBidDecision" AS ENUM ('PENDING', 'BID', 'NO_BID');

-- CreateEnum
CREATE TYPE "BidCriterionValue" AS ENUM ('YES', 'NO', 'NOT_EVALUATED');

-- CreateEnum
CREATE TYPE "NoBidReason" AS ENUM ('INSUFFICIENT_TIME', 'TECHNICAL_MISMATCH', 'RESOURCE_CONSTRAINT', 'COMMERCIAL_RISK', 'MISSING_QUALIFICATION', 'LOW_STRATEGIC_VALUE', 'LOW_MARGIN_EXPECTATION', 'OTHER');

-- CreateEnum
CREATE TYPE "TenderRequirementCategory" AS ENUM ('TECHNICAL', 'COMMERCIAL', 'LEGAL', 'ADMINISTRATIVE', 'FINANCIAL', 'CERTIFICATE', 'FORM', 'EXPERIENCE', 'BANK', 'SECURITY', 'OTHER');

-- CreateEnum
CREATE TYPE "TenderRequirementStatus" AS ENUM ('NOT_STARTED', 'IN_PROGRESS', 'READY_FOR_REVIEW', 'CHANGES_REQUIRED', 'APPROVED', 'NOT_APPLICABLE', 'BLOCKED');

-- CreateEnum
CREATE TYPE "TenderReviewGateType" AS ENUM ('TECHNICAL', 'COMMERCIAL', 'LEGAL', 'FINAL');

-- CreateEnum
CREATE TYPE "TenderReviewMode" AS ENUM ('ANY_ONE', 'ALL');

-- CreateEnum
CREATE TYPE "TenderReviewGateStatus" AS ENUM ('WAITING', 'OPEN', 'APPROVED', 'CHANGES_REQUIRED', 'REJECTED', 'SUPERSEDED');

-- CreateEnum
CREATE TYPE "TenderReviewStatus" AS ENUM ('PENDING', 'APPROVED', 'CHANGES_REQUIRED', 'REJECTED', 'SUPERSEDED');

-- CreateEnum
CREATE TYPE "TenderSubmissionMethod" AS ENUM ('GOVERNMENT_PORTAL', 'EMAIL', 'PHYSICAL', 'COURIER', 'OTHER');

-- CreateEnum
CREATE TYPE "TenderSubmissionKind" AS ENUM ('SUBMISSION', 'CORRECTION');

-- CreateEnum
CREATE TYPE "TenderLossReason" AS ENUM ('PRICE', 'TECHNICAL_SCORE', 'COMMERCIAL_TERMS', 'QUALIFICATION', 'DELIVERY_TIMELINE', 'CUSTOMER_DECISION', 'CANCELLED', 'UNKNOWN', 'OTHER');

-- CreateEnum
CREATE TYPE "TenderClarificationStatus" AS ENUM ('OPEN', 'SUBMITTED', 'ANSWERED', 'WITHDRAWN');

-- CreateEnum
CREATE TYPE "CommercialDocumentCategory" AS ENUM ('SOURCE_DOCUMENTS', 'ADDENDA', 'CLARIFICATIONS', 'TECHNICAL_SUBMISSION', 'COMMERCIAL_SUBMISSION', 'ADMINISTRATIVE', 'CERTIFICATES', 'BANKING', 'FINAL_SUBMISSION', 'PROOF_OF_SUBMISSION', 'SIGNED_CONTRACT', 'STATEMENT_OF_WORK', 'TECHNICAL_PROPOSAL', 'COMMERCIAL_PROPOSAL', 'ANNEX', 'AMENDMENT', 'EXTENSION', 'RENEWAL', 'ACCEPTANCE_CERTIFICATE', 'CORRESPONDENCE', 'OTHER');

-- CreateEnum
CREATE TYPE "DocumentClassification" AS ENUM ('GENERAL', 'COMMERCIAL_CONFIDENTIAL', 'LEGAL_RESTRICTED', 'BANKING_RESTRICTED');

-- CreateEnum
CREATE TYPE "CorporateDocumentType" AS ENUM ('COMMERCIAL_REGISTRATION', 'TAX_REGISTRATION', 'VAT_CERTIFICATE', 'ISO_CERTIFICATE', 'BANK_LETTER', 'COMPANY_PROFILE', 'PREVIOUS_EXPERIENCE', 'MANUFACTURER_AUTHORIZATION', 'LICENSE', 'INSURANCE_CERTIFICATE', 'OTHER');

-- CreateEnum
CREATE TYPE "CorporateDocumentStatus" AS ENUM ('ACTIVE', 'ARCHIVED');

-- CreateEnum
CREATE TYPE "ContractType" AS ENUM ('SUPPLY', 'SERVICES', 'MAINTENANCE', 'SUPPORT', 'IMPLEMENTATION', 'FRAMEWORK', 'LICENSE', 'OTHER');

-- CreateEnum
CREATE TYPE "ContractStatus" AS ENUM ('DRAFT', 'UNDER_REVIEW', 'AWAITING_SIGNATURE', 'ACTIVE', 'RENEWAL_REVIEW', 'SUSPENDED', 'EXPIRED', 'TERMINATED', 'CLOSED');

-- CreateEnum
CREATE TYPE "ContractRenewalType" AS ENUM ('NONE', 'FIXED_TERM', 'MANUAL_RENEWAL', 'AUTO_RENEWAL', 'EVERGREEN');

-- CreateEnum
CREATE TYPE "CommercialHealth" AS ENUM ('HEALTHY', 'NEEDS_ATTENTION', 'AT_RISK', 'CRITICAL');

-- CreateEnum
CREATE TYPE "ContractAmendmentType" AS ENUM ('VALUE_CHANGE', 'TIME_EXTENSION', 'SCOPE_CHANGE', 'COMMERCIAL_CHANGE', 'TECHNICAL_CHANGE', 'GENERAL');

-- CreateEnum
CREATE TYPE "ContractAmendmentStatus" AS ENUM ('DRAFT', 'UNDER_REVIEW', 'APPROVED', 'EFFECTIVE', 'REJECTED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "ObligationCategory" AS ENUM ('REPORTING', 'MAINTENANCE', 'SUPPORT', 'SLA', 'TRAINING', 'DELIVERY', 'PAYMENT_RELATED', 'CERTIFICATION', 'SECURITY', 'WARRANTY', 'OTHER');

-- CreateEnum
CREATE TYPE "ObligationCriticality" AS ENUM ('STANDARD', 'CRITICAL');

-- CreateEnum
CREATE TYPE "ObligationRecurrence" AS ENUM ('NONE', 'MONTHLY', 'QUARTERLY', 'YEARLY');

-- CreateEnum
CREATE TYPE "ObligationStatus" AS ENUM ('UPCOMING', 'IN_PROGRESS', 'COMPLETED', 'WAIVED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "MilestoneStatus" AS ENUM ('NOT_STARTED', 'IN_PROGRESS', 'SUBMITTED', 'APPROVED', 'COMPLETED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "GuaranteeType" AS ENUM ('BID_SECURITY', 'PERFORMANCE_GUARANTEE', 'ADVANCE_PAYMENT_GUARANTEE', 'WARRANTY_GUARANTEE', 'INSURANCE_CERTIFICATE', 'OTHER');

-- CreateEnum
CREATE TYPE "GuaranteeStatus" AS ENUM ('ACTIVE', 'EXPIRED', 'RELEASED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "RenewalActionType" AS ENUM ('REVIEW_STARTED', 'RENEW', 'DO_NOT_RENEW', 'NOTICE_SENT', 'RENEWED', 'EXTENDED');

-- AlterEnum
ALTER TYPE "AttachmentOwnerType" ADD VALUE 'COMMERCIAL_DOCUMENT';
ALTER TYPE "AttachmentOwnerType" ADD VALUE 'CORPORATE_DOCUMENT';
ALTER TYPE "AttachmentOwnerType" ADD VALUE 'TENDER_REQUIREMENT';
ALTER TYPE "AttachmentOwnerType" ADD VALUE 'OBLIGATION_OCCURRENCE';
ALTER TYPE "AttachmentOwnerType" ADD VALUE 'CONTRACT_MILESTONE';
ALTER TYPE "AttachmentOwnerType" ADD VALUE 'GUARANTEE';

-- AlterEnum
ALTER TYPE "NotificationCategory" ADD VALUE 'COMMERCIAL';
