import { Prisma } from '@company-ops/db';

/**
 * How each Prisma model relates to tenancy. Typed over every model name, so adding a model to the
 * schema without classifying it here fails compilation.
 *
 * - `tenant`: carries organization_id; every query must be bound to the active organization.
 * - `tenant-root`: the organizations table; only the active organization row is reachable.
 * - `global`: no organization_id by design (users: global identity, ADR-0012).
 * - `platform`: platform-only data (ADR-0010); never reachable through the tenant-scoped client.
 */
export type ModelTenancy = 'tenant' | 'tenant-root' | 'global' | 'platform';

export const MODEL_TENANCY: Readonly<Record<Prisma.ModelName, ModelTenancy>> = {
  Organization: 'tenant-root',
  User: 'global',
  OrganizationMember: 'tenant',
  Role: 'tenant',
  RolePermission: 'tenant',
  MemberRole: 'tenant',
  AuditLog: 'tenant',
  PlatformAuditLog: 'platform',
  Department: 'tenant',
  JobTitle: 'tenant',
  Team: 'tenant',
  TeamMember: 'tenant',
  EmployeeProfile: 'tenant',
  MemberInvitation: 'tenant',
  OrganizationCounter: 'tenant',
  Attachment: 'tenant',
  Notification: 'tenant',
  OutboxEvent: 'tenant',
  Customer: 'tenant',
  Project: 'tenant',
  ProjectMember: 'tenant',
  WorkLocation: 'tenant',
  ProjectLocation: 'tenant',
  DailyReport: 'tenant',
  ProjectActivity: 'tenant',
  SupportCategory: 'tenant',
  SupportComponent: 'tenant',
  BusinessCalendar: 'tenant',
  SlaPolicy: 'tenant',
  EscalationRule: 'tenant',
  SupportTicket: 'tenant',
  SupportTicketEvent: 'tenant',
  SupportTicketComment: 'tenant',
  SupportTicketWatcher: 'tenant',
  SlaEvent: 'tenant',
  NotificationDelivery: 'tenant',
  NotificationPreference: 'tenant',
  JiraConnection: 'tenant',
  JiraProjectMapping: 'tenant',
  JiraIssue: 'tenant',
  JiraSyncRun: 'tenant',
  JiraSyncFailure: 'tenant',
  JiraWebhookRegistration: 'tenant',
  JiraWebhookDelivery: 'tenant',
  SupportTicketJiraLink: 'tenant',
  JiraIssueCreateRequest: 'tenant',
  RetentionPolicy: 'tenant',
  GithubInstallation: 'tenant',
  GithubRepository: 'tenant',
  GithubRepositoryMapping: 'tenant',
  GithubPullRequest: 'tenant',
  GithubPrJiraLink: 'tenant',
  GithubWebhookDelivery: 'tenant',
  GithubSyncRun: 'tenant',
  GithubSyncFailure: 'tenant',
  SupportTicketGithubLink: 'tenant',
  RequestType: 'tenant',
  RequestTypeRole: 'tenant',
  WorkflowDefinition: 'tenant',
  WorkflowVersion: 'tenant',
  WorkflowStep: 'tenant',
  RequestInstance: 'tenant',
  RequestApproval: 'tenant',
  ApprovalDelegation: 'tenant',
  RequestEvent: 'tenant',
  RequestEffect: 'tenant',
  AttendancePolicy: 'tenant',
  Shift: 'tenant',
  EmployeeShiftAssignment: 'tenant',
  AttendanceRecord: 'tenant',
  AttendanceEvent: 'tenant',
  AttendanceAdjustmentRequest: 'tenant',
  Tender: 'tenant',
  TenderBidDecisionRecord: 'tenant',
  TenderRequirement: 'tenant',
  TenderRequirementLink: 'tenant',
  TenderReviewGate: 'tenant',
  TenderReview: 'tenant',
  TenderEvent: 'tenant',
  TenderAddendum: 'tenant',
  TenderClarification: 'tenant',
  TenderSubmission: 'tenant',
  CommercialDocument: 'tenant',
  CommercialDocumentVersion: 'tenant',
  CorporateDocument: 'tenant',
  CorporateDocumentVersion: 'tenant',
  Contract: 'tenant',
  ContractAmendment: 'tenant',
  ContractObligation: 'tenant',
  ContractObligationOccurrence: 'tenant',
  ContractMilestone: 'tenant',
  Guarantee: 'tenant',
  ContractEvent: 'tenant',
  ContractRenewalAction: 'tenant',
  CommercialReminder: 'tenant',
  CommercialSettings: 'tenant',
};

const fieldSet = (fields: Readonly<Record<string, string>>): ReadonlySet<string> => new Set(Object.values(fields));

/** Scalar (non-relation) fields per model, from the generated client. */
export const SCALAR_FIELDS: Readonly<Record<Prisma.ModelName, ReadonlySet<string>>> = {
  Organization: fieldSet(Prisma.OrganizationScalarFieldEnum),
  User: fieldSet(Prisma.UserScalarFieldEnum),
  OrganizationMember: fieldSet(Prisma.OrganizationMemberScalarFieldEnum),
  Role: fieldSet(Prisma.RoleScalarFieldEnum),
  RolePermission: fieldSet(Prisma.RolePermissionScalarFieldEnum),
  MemberRole: fieldSet(Prisma.MemberRoleScalarFieldEnum),
  AuditLog: fieldSet(Prisma.AuditLogScalarFieldEnum),
  PlatformAuditLog: fieldSet(Prisma.PlatformAuditLogScalarFieldEnum),
  Department: fieldSet(Prisma.DepartmentScalarFieldEnum),
  JobTitle: fieldSet(Prisma.JobTitleScalarFieldEnum),
  Team: fieldSet(Prisma.TeamScalarFieldEnum),
  TeamMember: fieldSet(Prisma.TeamMemberScalarFieldEnum),
  EmployeeProfile: fieldSet(Prisma.EmployeeProfileScalarFieldEnum),
  MemberInvitation: fieldSet(Prisma.MemberInvitationScalarFieldEnum),
  OrganizationCounter: fieldSet(Prisma.OrganizationCounterScalarFieldEnum),
  Attachment: fieldSet(Prisma.AttachmentScalarFieldEnum),
  Notification: fieldSet(Prisma.NotificationScalarFieldEnum),
  OutboxEvent: fieldSet(Prisma.OutboxEventScalarFieldEnum),
  Customer: fieldSet(Prisma.CustomerScalarFieldEnum),
  Project: fieldSet(Prisma.ProjectScalarFieldEnum),
  ProjectMember: fieldSet(Prisma.ProjectMemberScalarFieldEnum),
  WorkLocation: fieldSet(Prisma.WorkLocationScalarFieldEnum),
  ProjectLocation: fieldSet(Prisma.ProjectLocationScalarFieldEnum),
  DailyReport: fieldSet(Prisma.DailyReportScalarFieldEnum),
  ProjectActivity: fieldSet(Prisma.ProjectActivityScalarFieldEnum),
  SupportCategory: fieldSet(Prisma.SupportCategoryScalarFieldEnum),
  SupportComponent: fieldSet(Prisma.SupportComponentScalarFieldEnum),
  BusinessCalendar: fieldSet(Prisma.BusinessCalendarScalarFieldEnum),
  SlaPolicy: fieldSet(Prisma.SlaPolicyScalarFieldEnum),
  EscalationRule: fieldSet(Prisma.EscalationRuleScalarFieldEnum),
  SupportTicket: fieldSet(Prisma.SupportTicketScalarFieldEnum),
  SupportTicketEvent: fieldSet(Prisma.SupportTicketEventScalarFieldEnum),
  SupportTicketComment: fieldSet(Prisma.SupportTicketCommentScalarFieldEnum),
  SupportTicketWatcher: fieldSet(Prisma.SupportTicketWatcherScalarFieldEnum),
  SlaEvent: fieldSet(Prisma.SlaEventScalarFieldEnum),
  NotificationDelivery: fieldSet(Prisma.NotificationDeliveryScalarFieldEnum),
  NotificationPreference: fieldSet(Prisma.NotificationPreferenceScalarFieldEnum),
  JiraConnection: fieldSet(Prisma.JiraConnectionScalarFieldEnum),
  JiraProjectMapping: fieldSet(Prisma.JiraProjectMappingScalarFieldEnum),
  JiraIssue: fieldSet(Prisma.JiraIssueScalarFieldEnum),
  JiraSyncRun: fieldSet(Prisma.JiraSyncRunScalarFieldEnum),
  JiraSyncFailure: fieldSet(Prisma.JiraSyncFailureScalarFieldEnum),
  JiraWebhookRegistration: fieldSet(Prisma.JiraWebhookRegistrationScalarFieldEnum),
  JiraWebhookDelivery: fieldSet(Prisma.JiraWebhookDeliveryScalarFieldEnum),
  SupportTicketJiraLink: fieldSet(Prisma.SupportTicketJiraLinkScalarFieldEnum),
  JiraIssueCreateRequest: fieldSet(Prisma.JiraIssueCreateRequestScalarFieldEnum),
  RetentionPolicy: fieldSet(Prisma.RetentionPolicyScalarFieldEnum),
  GithubInstallation: fieldSet(Prisma.GithubInstallationScalarFieldEnum),
  GithubRepository: fieldSet(Prisma.GithubRepositoryScalarFieldEnum),
  GithubRepositoryMapping: fieldSet(Prisma.GithubRepositoryMappingScalarFieldEnum),
  GithubPullRequest: fieldSet(Prisma.GithubPullRequestScalarFieldEnum),
  GithubPrJiraLink: fieldSet(Prisma.GithubPrJiraLinkScalarFieldEnum),
  GithubWebhookDelivery: fieldSet(Prisma.GithubWebhookDeliveryScalarFieldEnum),
  GithubSyncRun: fieldSet(Prisma.GithubSyncRunScalarFieldEnum),
  GithubSyncFailure: fieldSet(Prisma.GithubSyncFailureScalarFieldEnum),
  SupportTicketGithubLink: fieldSet(Prisma.SupportTicketGithubLinkScalarFieldEnum),
  RequestType: fieldSet(Prisma.RequestTypeScalarFieldEnum),
  RequestTypeRole: fieldSet(Prisma.RequestTypeRoleScalarFieldEnum),
  WorkflowDefinition: fieldSet(Prisma.WorkflowDefinitionScalarFieldEnum),
  WorkflowVersion: fieldSet(Prisma.WorkflowVersionScalarFieldEnum),
  WorkflowStep: fieldSet(Prisma.WorkflowStepScalarFieldEnum),
  RequestInstance: fieldSet(Prisma.RequestInstanceScalarFieldEnum),
  RequestApproval: fieldSet(Prisma.RequestApprovalScalarFieldEnum),
  ApprovalDelegation: fieldSet(Prisma.ApprovalDelegationScalarFieldEnum),
  RequestEvent: fieldSet(Prisma.RequestEventScalarFieldEnum),
  RequestEffect: fieldSet(Prisma.RequestEffectScalarFieldEnum),
  AttendancePolicy: fieldSet(Prisma.AttendancePolicyScalarFieldEnum),
  Shift: fieldSet(Prisma.ShiftScalarFieldEnum),
  EmployeeShiftAssignment: fieldSet(Prisma.EmployeeShiftAssignmentScalarFieldEnum),
  AttendanceRecord: fieldSet(Prisma.AttendanceRecordScalarFieldEnum),
  AttendanceEvent: fieldSet(Prisma.AttendanceEventScalarFieldEnum),
  AttendanceAdjustmentRequest: fieldSet(Prisma.AttendanceAdjustmentRequestScalarFieldEnum),
  Tender: fieldSet(Prisma.TenderScalarFieldEnum),
  TenderBidDecisionRecord: fieldSet(Prisma.TenderBidDecisionRecordScalarFieldEnum),
  TenderRequirement: fieldSet(Prisma.TenderRequirementScalarFieldEnum),
  TenderRequirementLink: fieldSet(Prisma.TenderRequirementLinkScalarFieldEnum),
  TenderReviewGate: fieldSet(Prisma.TenderReviewGateScalarFieldEnum),
  TenderReview: fieldSet(Prisma.TenderReviewScalarFieldEnum),
  TenderEvent: fieldSet(Prisma.TenderEventScalarFieldEnum),
  TenderAddendum: fieldSet(Prisma.TenderAddendumScalarFieldEnum),
  TenderClarification: fieldSet(Prisma.TenderClarificationScalarFieldEnum),
  TenderSubmission: fieldSet(Prisma.TenderSubmissionScalarFieldEnum),
  CommercialDocument: fieldSet(Prisma.CommercialDocumentScalarFieldEnum),
  CommercialDocumentVersion: fieldSet(Prisma.CommercialDocumentVersionScalarFieldEnum),
  CorporateDocument: fieldSet(Prisma.CorporateDocumentScalarFieldEnum),
  CorporateDocumentVersion: fieldSet(Prisma.CorporateDocumentVersionScalarFieldEnum),
  Contract: fieldSet(Prisma.ContractScalarFieldEnum),
  ContractAmendment: fieldSet(Prisma.ContractAmendmentScalarFieldEnum),
  ContractObligation: fieldSet(Prisma.ContractObligationScalarFieldEnum),
  ContractObligationOccurrence: fieldSet(Prisma.ContractObligationOccurrenceScalarFieldEnum),
  ContractMilestone: fieldSet(Prisma.ContractMilestoneScalarFieldEnum),
  Guarantee: fieldSet(Prisma.GuaranteeScalarFieldEnum),
  ContractEvent: fieldSet(Prisma.ContractEventScalarFieldEnum),
  ContractRenewalAction: fieldSet(Prisma.ContractRenewalActionScalarFieldEnum),
  CommercialReminder: fieldSet(Prisma.CommercialReminderScalarFieldEnum),
  CommercialSettings: fieldSet(Prisma.CommercialSettingsScalarFieldEnum),
};

export function isModelName(value: string): value is Prisma.ModelName {
  return Object.hasOwn(MODEL_TENANCY, value);
}
